### ISSUE TITLE
[Plugin] Stop creating .styly in case of error

### ISSUE THREAD

**Issue by afjk** [styly-dev/STYLY-Spatial-Layer-Plugin#16]
### Pre-check
* OS ( Mac only )
* Unity Version (2023.3.x)
* Unity Module installed (Vision OS and iOS)

### Execution Error
* Build AssetBundle Failed.

### Ideal implementation
- show error
- do not create .styly fie

**Comment by from2001** [comment]
With the current version, even when an error occurs and the plugin doesn't create an asset bundle, .styly file is created.

The .styly file causes 500 error at the server side, but error message is not displayed at the upload page.

We need to implement
- Error handling at the server side
- Error handling at the plugin side. Don't create .styly file if error occurs @afjk

**Comment by from2001** [comment]
https://github.com/styly-dev/STYLY-Spatial-Layer-Plugin/pull/95
