### ISSUE TITLE
Videoplayer support for visionOS

### ISSUE THREAD

**Issue by from2001** [styly-dev/STYLY-Spatial-Layer-Plugin#41]
I will implement a Videoplayer helper script to

- [x] make Videoplayer component available on visionOS.
- [x] check Videoplayer component uses RenderTexture on visionOS. Alert if not using RenderTexture.
- [x] call `Unity.PolySpatial.PolySpatialObjectUtils.MarkDirty()` for the RenderTexture if PolySpatial is installed.
- [x] cache a video file if the source is URL and `WebRequest_VisualScriptingNodes` package is installed.
- [ ] ~~Display the description of the script on the inspector, such as the feature of the visionOS support, caching feature etc.~~
- [ ] ~~Display `fix` button on the inspector to solve the requirement issues. ~~
- [ ] ~~Add RequireComponent to the script~~

The VideoPlayerHelper script is intended to be attached to the same Gameobject which has a VideoPlayer component.

**Comment by from2001** [comment]
Code will be committed on the brunch of
https://github.com/styly-dev/STYLY-visionOS-Plugin/tree/issues/41_VideoPlayerSupport

**Comment by from2001** [comment]
The feature is now implemented and working fine.
I also added samples for the usage with [a free movie file](https://pixabay.com/videos/ocean-beach-waves-breaking-waves-160767/).

**Comment by from2001** [comment]
Videoclip doesn’t work with AssetBundle on visionOS.
I posted it to the[ Unity discussion forum](https://discussions.unity.com/t/videoclip-doesnt-work-with-assetbundle/354286).

**Comment by from2001** [comment]
Videoplayer support is released
https://github.com/styly-dev/STYLY-visionOS-Plugin/releases/tag/v0.1.5

**Comment by ku6ryo** [comment]
We do not do the rest of the tasks. (the dashed tasks in description)
