### ISSUE TITLE
Change Repository and Package name

### ISSUE THREAD

**Issue by styly-dev** [styly-dev/STYLY-Spatial-Layer-Plugin#54]
We'll change the names

`https://github.com/styly-dev/STYLY-visionOS-Plugin`
  =>
`https://github.com/styly-dev/STYLY-Spatial-Layer-Plugin`

`com.styly.styly-vision-os-plugin`
  =>
`com.styly.styly-spatial-layer-plugin`

**Comment by from2001** [comment]
Released
https://github.com/styly-dev/STYLY-Spatial-Layer-Plugin/releases/tag/v0.2.0

https://openupm.com/packages/com.styly.styly-spatial-layer-plugin/
