### ISSUE TITLE
STYLY-Vision-OS-App Crashes on Launch Due to DYLD_ROOT_PATH Not Set

### ISSUE THREAD

**Issue by masaharutennis** [styly-dev/STYLY-Spatial-Layer-Plugin#83]
I am encountering an issue when trying to launch the STYLY-Vision-OS-App after downloading it. The app crashes immediately with the following error:

```
Termination Reason: DYLD 9 
DYLD_ROOT_PATH not set for simulator program
```
Crash Report:

```
Incident Identifier: 92FD2D73-1EE2-49E7-9929-D48B33419591
CrashReporter Key:   768FC28F-811B-033A-E55A-29FAD6C46EE9
Hardware Model:      Mac14,9
Process:             STYLY-Vision-OS-App [73570]
Path:                /Volumes/VOLUME/*/STYLY-Vision-OS-App.app/STYLY-Vision-OS-App
Identifier:          com.styly.STYLY-Vision-OS-App
Version:             1.0.12 (0)
Code Type:           ARM-64 (Native)
Role:                Default
Parent Process:      launchd [1]
Coalition:           com.styly.STYLY-Vision-OS-App [78480]

Date/Time:           2024-05-17 22:44:56.6344 +0900
Launch Time:         2024-05-17 22:44:56.5693 +0900
OS Version:          macOS 14.4.1 (23E224)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: DYLD 9 
DYLD_ROOT_PATH not set for simulator program

Triggered by Thread:  0

Thread 0 Crashed:
0   dyld                          	       0x1008e5a50 __abort_with_payload + 8
1   dyld                          	       0x1008f0628 abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x1008f065c abort_with_payload + 16
3   dyld                          	       0x1008826b0 dyld4::halt(char const*, dyld4::StructuredError const*) + 304
4   dyld                          	       0x10087f31c dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4084
5   dyld                          	       0x10087dedc start + 1844
```
Steps to Reproduce:

Download the STYLY-Vision-OS-App.
Attempt to open the app from the Downloads folder.
System Information:

Model: MacBook Pro (Mac14,9)
Processor: Apple M2 Pro
macOS Version: 14.4.1 (23E224)
App Version: 1.0.12 (0)
Additional Notes:

It appears the app is failing to launch because the DYLD_ROOT_PATH environment variable is not set, which is required for the simulator program. Any guidance on how to resolve this issue would be appreciated.

**Comment by from2001** [comment]
@masaharutennis Thank you for your feedback.

We never have encountered the error, so I think it depends on your environment.

Could you tell me the version of the following?
- XCode
- visionOS simulator

Does it happen even after you restart your Mac?

**Comment by masaharutennis** [comment]
Thank you for your response.

My Xcode version is 15.3 and the simulated versions are iOS 17.4 and visionOS 1.1.

I restarted my Mac and tried to launch the app again, but it still does not work.

**Comment by from2001** [comment]
That’s strange. We’ll release new version of the app soon, so could you wait for it?

Xcode 14 has been also released. Please try with the latest app and simulator.

**Comment by from2001** [comment]
@masaharutennis 
New version of STYLY for Vision Pro and the plugin has been released.
Please try again with the latest version.

**Comment by from2001** [comment]
@masaharutennis I'll close this issue. If you still have the problem with the latest app and the simulator environment, don't hesitate to re-open this issue.
